### ISSUE TITLE
fitToBox broken with Z-axis Up

### ISSUE THREAD

**Issue by rxmarccall** [yomotsu/camera-controls#276]
## Describe the bug
The fitToBox function does not result in a Box3 being properly focused by the camera when `camera.up` is set to use the Z-axis. The issue is particularly noticeable when using a Box3 that has a much larger vertically than wide. (vertical rectangle)

## To Reproduce

1. Set the ThreeJS camera's `up` property to: `new Vector3(0, 0, 1);`
2. Call `cameraControls.updateCameraUp();`
3. Create a Box3 that's primarily vertical, see code below for values to try.
4. Call `this.cameraControls.fitToBox(tempBox3, false);`
### Code

```js
//init Camera
this.camera = new THREE.PerspectiveCamera(30, this.divRef.current.offsetWidth / this.divRef.current.offsetHeight, 0.1, 1000);

// Set camera's up to use Z axis
this.camera.up.set(0, 0, 1);
this.camera.position.z = 50;

// Create camera controls
this.cameraControls = new CameraControls( this.camera, this.renderer.domElement );

// Update camera controls 'Up' since we made camera's up use the Z axis
this.cameraControls.updateCameraUp();

// Create a vertical test Box3 for demonstrating fit to box issue and run fitToBox after a delay
setTimeout(() => {
const tempBox3 = new THREE.Box3();
tempBox3.setFromPoints([
    new THREE.Vector3(-10, -40, 0),
    new THREE.Vector3(10, 40, 5),
]);

const boxHelper = new THREE.Box3Helper(tempBox3);
this.scene.add(boxHelper);

this.cameraControls.fitToBox(tempBox3, false);
}, 2000);
```

### Live example
NA

## Expected behavior
fitToBox should focus / fit a Box3 correctly regardless of Camera's up axis or a Box3's dimensions.

## Screenshots or Video
Result with camera's up set to Z axis
![image](https://user-images.githubusercontent.com/1920223/174898839-d9f355c1-2af0-497f-a5df-e33a70208c9c.png)
Result with camera's standard up orientation
![image](https://user-images.githubusercontent.com/1920223/174898889-5bb3704f-26cb-4cc0-ad8b-e08b12301c77.png)

## Platform:

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]

**Comment by yomotsu** [comment]
Thanks for your report. I'll take a look.

**Comment by yomotsu** [comment]
Reproduced the problem. marked as a bug.

**Comment by yomotsu** [comment]
@rxmarccall I think this has been fixed with PR: #279 and v1.34.6 has been released.

**Comment by rxmarccall** [comment]
Thanks @yomotsu 
I gave it a try and it seems to mostly be fixed, but might have a slight issue still. In my test there is a slight offset, so that the object is not centered completely. Here I did a padding of 5 for each side, and you'll notice that there is more space below than above. The issue happens with no padding set as well.

<img width="1025" alt="Screen Shot 2022-06-27 at 10 40 22 AM" src="https://user-images.githubusercontent.com/1920223/175992304-51a455b7-b78c-443d-b9bc-69c6583d69a7.png">

**Comment by yomotsu** [comment]
Uh oh, do you mind providing a simplified standalone example, please?

**Comment by rxmarccall** [comment]
Here is what I used for the above example:

```
import React from 'react';
import * as THREE from 'three';
import CameraControls from 'camera-controls';
import MetalSphere from '../Components/3D/MetalSphere.three';
import Loading from './../Components/Loading.component';
import { handleSceneResize, initEventListener } from './../Utils/sceneResize';

export default class MainScene extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            loading: this.props.loading ? true : false,
        }
        //3D Scene components
        this.divRef = React.createRef();
        this.renderer = null;
        this.camera = null;
        this.scene = null;
    }

    componentDidMount() {
        this.initScene();
    }
    initScene = () => {

        CameraControls.install( { THREE: THREE } );

        //init Loading Manager
        const loadingManager = new THREE.LoadingManager();
        loadingManager.onLoad = () => {
            this.setState({ loading: false }, () => { })
        }

        this.clock = new THREE.Clock();

        //init Renderer
        this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
        this.renderer.setPixelRatio(window.devicePixelRatio);
        this.renderer.autoClear = false;
        this.renderer.setClearColor(new THREE.Color(0x222222));
        this.renderer.setSize(this.divRef.current.offsetWidth, this.divRef.current.offsetHeight);
        this.divRef.current.appendChild(this.renderer.domElement);

        //init Scene
        this.scene = new THREE.Scene();
        this.scene.background = new THREE.Color(0x222222);

        //init Camera
        this.camera = new THREE.PerspectiveCamera(30, this.divRef.current.offsetWidth / this.divRef.current.offsetHeight, 0.1, 1000);
        // Set camera's up to use Z axis
        this.camera.up.set(0, 0, 1);
        this.camera.position.z = 50;

        this.cameraControls = new CameraControls( this.camera, this.renderer.domElement );
        // Update camera controls 'Up' since we made camera's up be the Z axis
        this.cameraControls.updateCameraUp();

        //Metal Sphere
        let sphere = new MetalSphere().create(loadingManager);
        this.scene.add(sphere);

        //Ambient Light
        let ambientLight = new THREE.AmbientLight(0x07215c);
        ambientLight.color.setRGB(0.02, 0.02, 0.07);
        ambientLight.intensity = 5;
        this.scene.add(ambientLight);

        //Directional Light
        let directionalLight = new THREE.DirectionalLight(0xe8f7ff, 1);
        directionalLight.position.set(1, 0, 5);
        this.scene.add(directionalLight);

        //init Handle Resize
        handleSceneResize(this.camera, this.renderer)
        initEventListener();

        // Create a test dummy Box3 for demonstrating fit to box issue
        setTimeout(() => {
        const tempBox3 = new THREE.Box3();
        tempBox3.setFromPoints([
            new THREE.Vector3(-20, -40, 0),
            new THREE.Vector3(20, 40, 5),
        ]);
    
        const boxHelper = new THREE.Box3Helper(tempBox3);
        this.scene.add(boxHelper);
    
        this.cameraControls.fitToBox(tempBox3, false, {paddingLeft: 5, paddingRight: 5, paddingBottom: 5, paddingTop: 5});
        }, 2000);

        //Animation Loop
        const animate = () => {
            requestAnimationFrame(animate);
            this.renderer.render(this.scene, this.camera);
            this.cameraControls.update(this.clock.getDelta());
            if (sphere) {
                let rotationRad = THREE.MathUtils.degToRad(.1);
                sphere.rotateY(rotationRad);
                sphere.rotateX(rotationRad);
                sphere.rotateZ(rotationRad);
            }

        }
        animate();
    }

    render() {
        return (<>
            <div className="three-container" ref={this.divRef}></div>
            {this.state.loading ? <Loading /> : ''}
        </>)

    }
}
```

**Comment by yomotsu** [comment]
Thanks for the code but sorry, I expected a "**simplified standalone**" one without extra libraries, modules, and bundler, just run on web browsers natively, just like camera-controls's official examples.
(Otherwise, I need to read the entire code to understand, and need setup to reproduce🥲)

Anyway, as you mentioned it seems padding option still causes the problem, right?
I will take a look.

**Comment by yomotsu** [comment]
I think the padding option has also been fixed.
Can you try with dev branch? here is the rawgit for it.

- esm: http://raw.githack.com/yomotsu/camera-controls/dev/dist/camera-controls.module.js
- umd: http://raw.githack.com/yomotsu/camera-controls/dev/dist/camera-controls.js

**Comment by rxmarccall** [comment]
@yomotsu Sorry for the delay, just now got around to testing out your changes.
From what I can tell, it appears to be working correctly now! Thanks for figuring this out, should be good to merge and close.
